version: '3'
services:
  web:          # project name - can be any name
    build:
      context: .                    # all the files for project come from the current directory
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules           # don't map any local folder against /app/node_modules inside the container
      - .:/app                      # map the current folder outside the container to /app folder inside the container
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]